# Step 1: Build the app
FROM 689960076039.dkr.ecr.us-east-1.amazonaws.com/node-baseimage:latest AS builder

# Set working directory
WORKDIR /app

# Copy package.json and lock file
COPY package*.json ./

#RUN npm install -g npm@latest   

# Install dependencies
RUN npm ci

# Copy all source code
COPY . .

# Build the production-ready app
RUN npm run build


# Step 2: Serve the app using a lightweight web server (nginx)
FROM public.ecr.aws/nginx/nginx:alpine

# Copy built files from builder
COPY --from=builder /app/dist /usr/share/nginx/html

# Expose port 80
EXPOSE 80

# Start nginx
CMD ["nginx", "-g", "daemon off;"]

